substitutions:
  friendly_name: ""

esphome:
  name: ${device_name}
  comment: ${friendly_name}

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

web_server:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: ${device_name} WiFi Signal

text_sensor:
  - platform: version
    name: ${device_name} Version


