substitutions:
  friendly_name: ""

esphome:
  name: ${device_name}
  comment: ${friendly_name}

logger:
#  esp8266_store_log_strings_in_flash: false

wifi:
  fast_connect: True
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

web_server:
  port: 80
  local: false
  ota: false
  version: 3
#  js_url: "file:///D:/Work/Automatic/HomeAssistant/ESP/ESPHome/www.js"
  js_url: "http://192.168.1.111:8123/local/www.js"

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password


sensor:
  - platform: wifi_signal
    name: ${device_name} WiFi Signal



#time:
#  - platform: homeassistant
#    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${device_name} Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${device_name} IP
