packages:
  - !include common.yaml

substitutions:
  device_name: "istar"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: components

esp32_ble_tracker:

ble_client:
  - id: ble_istar1
    mac_address: 2B:80:03:D9:3E:8E

light:
  - platform: istar
    ble_client_id: ble_istar1
    name: ${device_name} Light
#    default_transition_length: 0s

sensor:
  - platform: ble_rssi
    mac_address: 2B:80:03:D9:3E:8E
    name: ${device_name} RSSI value
